#!/bin/bash

SCALE=( 0.4 0.5 0.6 0.7 0.8 0.9 1.0 )

cur=`cat /home/alex/.zoomstatus 2>/dev/null`

if [ "$cur" == "" ]; then
    cur=3
fi

if [ "$1" == "-" ]; then
    cur=$(( $cur + 1 ))
    if [ "$cur" -ge ${#SCALE[@]} ]; then exit;  fi
fi
if [ "$1" == "+" ]; then
    cur=$(( $cur - 1 ))
    if [ "$cur" -lt 0 ]; then exit;  fi
fi

xrandr --output eDP1 --scale 1x1
xrandr --output eDP1 --scale ${SCALE[$cur]}x${SCALE[$cur]} 

echo $cur > /home/alex/.zoomstatus

